### PR TITLE
Fix shotguns #65

### PR DESCRIPTION
**Pull request by karimcambridge**

### CODE REVIEW

**Comment by ziggi** [comment]
Maybe `WEAPON_SHOTGUN` leave on the old place? Instead of ` || byteWeaponId == WEAPON_SHOTGUN`.

**Comment by karimcambridge** [comment]
No, WEAPON_SHOTGUN would need it's own then, it would still need to be set to WEAPONSTATE_NO_BULLETS.

I'll add it that way.

**Comment by karimcambridge** [comment]
Done.

**Comment by ziggi** [comment]
Not completely :).
image

**Comment by karimcambridge** [comment]
Meh. Waste of commits..

**Pull request merged**
