### PR TITLE
Update CA to latest version

### PR DESCRIPTION
**Pull request by AmyrAhmady**
basically what title says, and doing some other minor changes

### CODE REVIEW

**Comment by AmyrAhmady** [comment]
just checked Releases tab, seems like you're not adding to version number, should I change it back to `200`/`2.0.0` or let it be `201`/`2.0.1` ? I've noticed you are adding them as RC

**Comment by Jedrzej94** [comment]
Tested on Linux & Windows. Works perfectly fine.

**Comment by WoutProvost** [comment]
> just checked Releases tab, seems like you're not adding to version number, should I change it back to `200`/`2.0.0` or let it be `201`/`2.0.1` ? I've noticed you are adding them as RC

Yes, revert 6ae4c9d.

**Comment by AmyrAhmady** [comment]
Done, also added a check for enforcing -A Win32

**Pull request merged**
