### PR TITLE
Train Speed

### PR DESCRIPTION
**Pull request by WoutProvost**
Added some small fixes as well.

### CODE REVIEW

**Comment by ziggi** [comment]
Looks good

**Comment by ziggi** [comment]
Also how this fixes #115?

**Comment by WoutProvost** [comment]
It allows the user to manually set the train speed, as asked. Or was the intention something different?

**Comment by WoutProvost** [comment]
People shouldn't be using FCNPC_Go... with trains. Just set the trainspeed and the train moves along the tracks.

**Comment by ziggi** [comment]
> People shouldn't be using FCNPC_Go... with trains. Just set the trainspeed and the train moves along the tracks.

Then we need to update the position of the train to make synchronization work.

**Pull request merged**
